CREATE TABLE APP_SERVICES
(
  ID   BIGSERIAL,
  NAME VARCHAR,
  TYPE VARCHAR,
  HOST VARCHAR
);
CREATE INDEX ID_TYPE_APP_SRVS_IDX ON APP_SERVICES (ID, TYPE);

CREATE TABLE PROPERTIES
(
  ID    BIGSERIAL,
  KEY   VARCHAR,
  VALUE VARCHAR
);
CREATE INDEX ID_KEY_PRPRTS_IDX ON PROPERTIES (ID, KEY);

CREATE TABLE LOGINS
(
  ID      BIGSERIAL,
  LOGIN   VARCHAR,
  USER_ID BIGINT
);
CREATE INDEX ID_LOGIN_LGNS_IDX ON LOGINS (ID, LOGIN);

CREATE TABLE AUTH_NODES_USERS
(
  ID_NODE BIGINT,
  ID_USER BIGINT
);
CREATE INDEX ID_ID_ANU_IDX ON AUTH_NODES_USERS (ID_NODE, ID_USER);

CREATE TABLE AUTH_NODES
(
  ID   BIGSERIAL,
  NAME VARCHAR,
  URL  VARCHAR
);
CREATE INDEX ID_ATHNDS_IDX ON AUTH_NODES (ID);


CREATE TABLE PASSWORDS
(
  ID       BIGSERIAL,
  PASSWORD VARCHAR,
  USER_ID  BIGINT
);
CREATE INDEX ID_PASS_PASSWD_IDX ON PASSWORDS (ID, USER_ID);

CREATE TABLE TOKENS
(
  ID      BIGSERIAL,
  TOKEN   VARCHAR,
  USER_ID BIGINT,
  EXPIRED TIMESTAMP
);
CREATE INDEX ID_TOKEN_TKNS_IDX ON TOKENS (ID, TOKEN);

CREATE TABLE TELEGRAM_CHANNELS
(
  ID               BIGSERIAL,
  USER_ID          BIGINT,
  NAME             VARCHAR,
  USER_TELEGRAM_ID BIGINT
);
CREATE INDEX USER_ID_TLGM_CH_IDX ON TELEGRAM_CHANNELS (USER_ID);
CREATE INDEX USER_TLGM_ID_TLGM_CH_IDX ON TELEGRAM_CHANNELS (USER_TELEGRAM_ID);

CREATE TABLE TELEGRAM_USERS
(
  ID            BIGSERIAL,
  USER_ID       BIGINT,
  TOKEN         VARCHAR,
  NAME          VARCHAR,
  ID_TLGM       BIGINT,
  IS_BOT        BOOLEAN,
  LAST_NAME     VARCHAR,
  USER_NAME     VARCHAR,
  LANGUAGE_CODE VARCHAR
);
CREATE INDEX ID_USER_TLGMUSERS_IDX ON TELEGRAM_USERS (ID, USER_ID);


CREATE TABLE USERS
(
  ID          BIGSERIAL,
  NAME        VARCHAR,
  SUR_NAME    VARCHAR,
  MIDDLE_NAME VARCHAR
);
CREATE INDEX ID_USRES_IDX ON USERS (ID);

CREATE TABLE VK_CONNECTORS
(
  ID              BIGSERIAL,
  TYPE            VARCHAR,
  USER_ID         BIGINT,
  VK_ACCESS_TOKEN VARCHAR,
  VK_USER_ID      BIGINT
);
CREATE INDEX USERID_TYPE_VKCONNTRS_IDX ON VK_CONNECTORS (USER_ID, TYPE);

create table VK_GROUPS
(
  ID              BIGSERIAL,
  USER_ID         BIGINT,
  VK_ID           BIGINT,
  NAME            VARCHAR,
  AVATAR_URL      VARCHAR
);
CREATE INDEX USERID_VKID_VKGRPS_IDX ON VK_GROUPS (USER_ID, vk_id);